// AUTO-GENERATED by scripts/generate-shipped-content.mjs - do not edit by hand.
// Source of truth: content/shipped/<category>/<slug>/{meta.json, cover.*}
// Run `npm run content:sync` to regenerate after adding/editing content.

import type { Platform } from "./work-data";

export type ShippedCard = {
  name: string;
  desc: string;
  platforms: Platform[];
  url: string;
  /** Screenshot to show in the image variant. Omit to render a label/text-only card. */
  image?: string;
  /** True if the cover image already includes its own device frame/bezel. */
  framed?: boolean;
};

export type ShippedCategory = {
  slug: string;
  title: string;
  cards: ShippedCard[];
};

export const shippedCategories: ShippedCategory[] = [
  {
    "slug": "mobile-ios",
    "title": "Mobile & iOS",
    "cards": [
      {
        "name": "Asset Infinity",
        "desc": "Enterprise asset tracking & management platform",
        "platforms": [
          "iOS",
          "Android",
          "Web"
        ],
        "url": "https://apps.apple.com/in/app/asset-infinity-v2/id1641535604",
        "image": "/assets/shipped/mobile-ios/asset-infinity.webp"
      },
      {
        "name": "AutoBeacon",
        "desc": "Connected automotive diagnostics & companion app",
        "platforms": [
          "iOS"
        ],
        "url": "https://apps.apple.com/in/app/autobeacon/id1597764990",
        "image": "/assets/shipped/mobile-ios/autobeacon.webp"
      },
      {
        "name": "Karching Driver Education",
        "desc": "Certified driver training & examination platform",
        "platforms": [
          "iOS"
        ],
        "url": "https://apps.apple.com/us/app/karching-driver-education/id1479901287",
        "image": "/assets/shipped/mobile-ios/karching.webp"
      },
      {
        "name": "Live Kirtan",
        "desc": "Spiritual streaming platform with live audio & community",
        "platforms": [
          "iOS",
          "Android"
        ],
        "url": "https://apps.apple.com/in/app/live-kirtan/id562758691",
        "image": "/assets/shipped/mobile-ios/live-kirtan.webp"
      },
      {
        "name": "MProtekt Gold",
        "desc": "GPS vehicle tracking & fleet management app",
        "platforms": [
          "iOS"
        ],
        "url": "https://apps.apple.com/in/app/m-protekt-gold/id1471286583",
        "image": "/assets/shipped/mobile-ios/mprotekt-gold.png",
        "framed": true
      },
      {
        "name": "QuizzyPop",
        "desc": "Daily educational quiz app for children - free, no ads",
        "platforms": [
          "Android"
        ],
        "url": "https://play.google.com/store/apps/details?id=com.quizzypop.app",
        "image": "/assets/shipped/mobile-ios/quizzypop.webp"
      }
    ]
  },
  {
    "slug": "website",
    "title": "Website / Web Development",
    "cards": [
      {
        "name": "CuraNet",
        "desc": "Secure health records, appointments & consent platform",
        "platforms": [
          "Web"
        ],
        "url": "https://curanet.in/",
        "image": "/assets/shipped/website/curanet.png"
      },
      {
        "name": "Kuriersoft",
        "desc": "Courier & logistics software suite",
        "platforms": [
          "Web"
        ],
        "url": "https://kuriersoft.in/",
        "image": "/assets/shipped/website/kuriersoft.png"
      },
      {
        "name": "KurierWalla",
        "desc": "Logistics & last-mile delivery management system",
        "platforms": [
          "Web"
        ],
        "url": "https://kurierwalla.com/",
        "image": "/assets/shipped/website/kurierwalla.png"
      },
      {
        "name": "PGKhata",
        "desc": "PG billing, rent collection & tenant management platform",
        "platforms": [
          "Web"
        ],
        "url": "https://pgkhata.com/",
        "image": "/assets/shipped/website/pgkhata.png"
      },
      {
        "name": "RGRT Group",
        "desc": "Corporate site for a multi-vertical business group",
        "platforms": [
          "Web"
        ],
        "url": "https://rgrtgroup.com/",
        "image": "/assets/shipped/website/rgrt-group.png"
      },
      {
        "name": "Shotup",
        "desc": "Premium visual studio & award-winning photography portfolio",
        "platforms": [
          "Web"
        ],
        "url": "https://shotup.in/",
        "image": "/assets/shipped/website/shotup.png"
      },
      {
        "name": "The Dark Store",
        "desc": "Black-first fashion & streetwear e-commerce store",
        "platforms": [
          "Web"
        ],
        "url": "https://thedarkstore.in/",
        "image": "/assets/shipped/website/the-dark-store.png"
      }
    ]
  }
];
