export type BlogPost = { slug: string; title: string; excerpt: string; publishedAt: string; readTime: string; body: string[] };

/** Add one entry here each day; the index and individual blog routes update automatically. */
export const blogPosts: BlogPost[] = [
  { slug: "shipping-a-product-is-a-system", title: "Shipping a product is a system, not a launch day", excerpt: "The decisions that make a release dependable begin long before the deploy button.", publishedAt: "2026-09-05", readTime: "3 min read", body: ["A reliable launch is the result of small decisions made consistently: clear product intent, an implementation that respects real constraints, and a release plan that can be observed after it ships.", "The interface is only one part of the product. Its data model, operating workflows, edge states, and handoff to the people who run it determine whether the release earns trust.", "That is why we treat the path from discovery through delivery as a connected system. Every stage should make the next stage clearer, not create expensive surprises later."] },
  { slug: "designing-for-the-second-use", title: "Designing for the second use", excerpt: "First impressions matter, but repeat use is where a product proves its value.", publishedAt: "2026-09-04", readTime: "2 min read", body: ["A first session introduces a product. The second session reveals whether people can find their place again without having to relearn the interface.", "Good product design preserves context: it shows what changed, gives important work a predictable home, and keeps routine actions close at hand.", "When a product is built around the return visit, it becomes easier to use under real conditions—when attention is limited and the task matters."] },
  { slug: "what-a-live-product-portfolio-proves", title: "What a live-product portfolio actually proves", excerpt: "A portfolio is more useful when it shows the kinds of products that exist beyond the presentation layer.", publishedAt: "2026-09-03", readTime: "2 min read", body: ["A static mockup can communicate taste. A live product adds evidence of a different kind: an experience that has to work across real devices, workflows, and changing needs.", "The best project archive gives visitors enough context to understand the business, the people it serves, and the public product experience without claiming work that cannot be verified.", "That balance is why a clear archive matters. It helps future partners recognize the patterns that are relevant to their own product."] },
];

export function getBlogPost(slug: string) { return blogPosts.find((post) => post.slug === slug); }
