import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { Footer } from "@/components/site/footer";
import { SiteNav } from "@/components/site/nav";
import { blogPosts } from "@/content/blog";

export const metadata: Metadata = { title: "Product Engineering Blog", description: "Daily product engineering, app development, web development, design, and delivery notes from AppCraft Technology.", alternates: { canonical: "https://appcraft.in/blog" }, openGraph: { title: "Product Engineering Blog | AppCraft Technology", description: "Daily notes on product engineering, design, and shipping digital products.", url: "https://appcraft.in/blog", type: "website" } };

export default function BlogPage() {
  return <div className="min-h-screen bg-background text-foreground"><SiteNav /><main className="pt-28 pb-20 sm:pt-36"><div className="mx-auto max-w-5xl px-5 sm:px-8"><h1 className="max-w-3xl text-4xl sm:text-5xl lg:text-6xl">Product engineering notes for teams building what is next.</h1><p className="mt-6 max-w-2xl text-base leading-7 text-ink-muted sm:text-lg">Daily, people-first notes on product engineering, app development, web development, design, and delivery. Every post is written to answer a practical question clearly, with useful context rather than SEO filler.</p><div className="mt-12 border-t border-line">{blogPosts.map((post) => <article key={post.slug} className="grid gap-5 border-b border-line py-7 sm:grid-cols-[10rem_minmax(0,1fr)_auto] sm:items-center"><div className="text-sm text-ink-dim"><time dateTime={post.publishedAt}>{post.publishedAt}</time><span className="mx-2">·</span>{post.readTime}</div><div><h2 className="text-2xl">{post.title}</h2><p className="mt-2 text-sm leading-6 text-ink-muted">{post.excerpt}</p></div><Link href={`/blog/${post.slug}`} className="inline-flex min-h-11 items-center gap-2 self-start rounded-full border border-line px-4 py-2 text-sm font-medium text-ink outline-none transition-colors hover:border-line-strong hover:bg-surface focus-visible:ring-2 focus-visible:ring-accent-blue-bright focus-visible:ring-offset-2 focus-visible:ring-offset-background sm:self-auto">Read <ArrowRight className="size-4" aria-hidden /></Link></article>)}</div><section className="mt-16 border-t border-line pt-8" aria-labelledby="blog-faq-title"><h2 id="blog-faq-title" className="text-3xl">About this blog</h2><dl className="mt-6 grid gap-7 sm:grid-cols-3"><div><dt className="text-lg font-semibold text-ink">What do we publish?</dt><dd className="mt-2 text-sm leading-6 text-ink-muted">Clear notes about building, designing, and shipping production mobile and web products.</dd></div><div><dt className="text-lg font-semibold text-ink">Who is it for?</dt><dd className="mt-2 text-sm leading-6 text-ink-muted">Product teams, founders, and operators evaluating a digital product or improving one already in use.</dd></div><div><dt className="text-lg font-semibold text-ink">How are posts maintained?</dt><dd className="mt-2 text-sm leading-6 text-ink-muted">Each post has a published date and can be updated as the product, platform, or practice it describes changes.</dd></div></dl></section></div></main><Footer /></div>;
}
